// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_nJ5Bd1o8L4vaih4AEIJoj5ISXvf8K4w',
    appId: '1:1064068149586:web:f2184d9c36673168f0ca8b',
    messagingSenderId: '1064068149586',
    projectId: 'firstfirebaseproject-304ca',
    authDomain: 'firstfirebaseproject-304ca.firebaseapp.com',
    storageBucket: 'firstfirebaseproject-304ca.appspot.com',
    measurementId: 'G-XE9R8XSXSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQkM8iKuCNFeW96p1gXivup9-aACW8Lkk',
    appId: '1:1064068149586:android:7aadba8b679a2f58f0ca8b',
    messagingSenderId: '1064068149586',
    projectId: 'firstfirebaseproject-304ca',
    storageBucket: 'firstfirebaseproject-304ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYXuhvw5q6aXcxpFdOIQbqiMP-uyiEi44',
    appId: '1:1064068149586:ios:8776a004009e4524f0ca8b',
    messagingSenderId: '1064068149586',
    projectId: 'firstfirebaseproject-304ca',
    storageBucket: 'firstfirebaseproject-304ca.appspot.com',
    androidClientId: '1064068149586-jmgrg79sktv80gctmr28rb0i0p0grnra.apps.googleusercontent.com',
    iosClientId: '1064068149586-fm5kq0ej1m7cva8dd1l28rr9r4dtulbn.apps.googleusercontent.com',
    iosBundleId: 'com.sonbol.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYXuhvw5q6aXcxpFdOIQbqiMP-uyiEi44',
    appId: '1:1064068149586:ios:8776a004009e4524f0ca8b',
    messagingSenderId: '1064068149586',
    projectId: 'firstfirebaseproject-304ca',
    storageBucket: 'firstfirebaseproject-304ca.appspot.com',
    androidClientId: '1064068149586-jmgrg79sktv80gctmr28rb0i0p0grnra.apps.googleusercontent.com',
    iosClientId: '1064068149586-fm5kq0ej1m7cva8dd1l28rr9r4dtulbn.apps.googleusercontent.com',
    iosBundleId: 'com.sonbol.socialApp',
  );
}
